[pytest]
filterwarnings =
    ignore::marshmallow.warnings.RemovedInMarshmallow4Warning
    ignore::marshmallow.warnings.ChangedInMarshmallow4Warning
    ignore:Type google\._upb\._message\..*:DeprecationWarning
    ignore:distutils Version classes are deprecated.*:DeprecationWarning:pyspark\.sql\.pandas\.utils

markers =
    integration: tests that exercise multiple components together