from math import sqrt
import numpy as np
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    median_absolute_error,
    r2_score
)
import mlflow


def mape(y_true, y_pred) -> float:
    """
    Calculate the Mean Absolute Percentage Error (MAPE).

    MAPE measures the average prediction error as a percentage of the actual
    values. It is useful for understanding model error in relative terms rather
    than absolute sales values.

    Any zero actual values are replaced with a very small number to avoid
    division by zero.

    Args:
        y_true: Actual target values.
        y_pred: Predicted target values.

    Returns:
        float: Mean absolute percentage error.
    """
    y_true = np.array(y_true, dtype=float)
    y_pred = np.array(y_pred, dtype=float)
    denom = np.where(y_true == 0, 1e-9, y_true)
    return np.mean(np.abs((y_true - y_pred) / denom)) * 100.0


def calculate_regression_metrics(y_test, preds) -> None:
    """
    Calculate, print, and log regression metrics for model evaluation.

    Compares the model predictions against the actual test target values and
    calculates several regression metrics, including MAE, RMSE, MAPE, R2,
    Median Absolute Error, Bias, and WAPE. The results are printed to the
    console for pipeline logs and logged to MLflow for experiment tracking.

    Args:
        y_test: Actual target values from the test dataset.
        preds: Predicted target values generated by the model.

    Returns:
        None
    """

    mae = mean_absolute_error(y_test, preds)
    rmse = sqrt(mean_squared_error(y_test, preds))
    mp = mape(y_test, preds)
    r2 = r2_score(y_test, preds)
    medae = median_absolute_error(y_test, preds)
    bias = np.mean(preds - y_test)
    wape = np.sum(np.abs(y_test - preds)) / np.sum(np.abs(y_test)) * 100

    print(f"MAE: {mae:,.0f}")
    print(f"RMSE: {rmse:,.0f}")
    print(f"MAPE: {mp:.2f}%")
    print(f"R2: {r2:.4f}")
    print(f"Median AE: {medae:,.0f}")
    print(f"BIAS: {bias:,.2f}")
    print(f"WAPE: {wape:.2f}%")

    mlflow.log_metric("MAE", mae)
    mlflow.log_metric("RMSE", rmse)
    mlflow.log_metric("MAPE", mp)
    mlflow.log_metric("R2", r2)
    mlflow.log_metric("Median_AE", medae)
    mlflow.log_metric("Bias", bias)
    mlflow.log_metric("WAPE", wape)
