$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: ${RT_DEPLOYMENT_NAME}
endpoint_name: ${RT_ENDPOINT_NAME}
model: azureml:${MODEL_NAME}:${MODEL_VERSION}
environment: azureml:${ENDPOINT_ENVIRONMENT}
instance_type: ${INSTANCE_TYPE}
instance_count: 1
environment_variables:
  MLFLOW_MODEL_FOLDER: model
  AML_SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}
  DATA_WORKSPACE_RG: ${RG}
  DATA_WORKSPACE_NAME: ${WORKSPACE_NAME}
  FEATURE_DATA_ASSET_NAME: ${FEATURE_DATA_ASSET_NAME}
  FEATURE_DATA_ASSET_VERSION: ${FEATURE_DATA_ASSET_VERSION}
app_insights_enabled: false
egress_public_network_access: enabled
liveness_probe:
  failure_threshold: 30
  initial_delay: 600
  period: 10
  success_threshold: 1
  timeout: 2
readiness_probe:
  failure_threshold: 30
  initial_delay: 10
  period: 10
  success_threshold: 1
  timeout: 2
request_settings:
  max_concurrent_requests_per_instance: 1
  request_timeout_ms: 90000
code_configuration:
  code: ..
  scoring_script: src/walmart_ml/score_scripts/${SCORE_SCRIPT}